# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$all\
$character$directory
"""

[character]
success_symbol = "[λ](cyan)"
error_symbol = "[λ](red)"
